// omo-tps-plus: runs senpi's own tps extension, adds when the last reply started and when its prompt cache expires,
// and keeps the minutes the cache has left in the footer.
// Installed as <agentDir>/extensions/tps.js in place of the generated shim. OMO rewrites that file only
// while it starts with its "// Generated by" banner, so this copy survives updates; delete it to get the
// stock shim back on the next start.
import { existsSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import * as senpi from "@code-yeongyu/senpi";
import * as piAi from "@earendil-works/pi-ai";

/** Same lookup as senpi's resource-loader uses for the shim it generates. */
export function upstreamPath(packageDir) {
	const flat = join(packageDir, "core", "extensions", "builtin", "tps.js");
	return existsSync(flat) ? flat : join(packageDir, "dist", "core", "extensions", "builtin", "tps.js");
}

export function clock(ms) {
	const date = new Date(ms);
	return [date.getHours(), date.getMinutes(), date.getSeconds()].map((n) => String(n).padStart(2, "0")).join(":");
}

export function cacheTtlSeconds(model) {
	if (!model || typeof piAi.resolvePromptCacheTtlSeconds !== "function") return undefined;
	try {
		const seconds = piAi.resolvePromptCacheTtlSeconds(model);
		return Number.isFinite(seconds) && seconds > 0 ? seconds : undefined;
	} catch {
		return undefined;
	}
}

const STATUS_KEY = "cache-ttl";

/** Footer text for a cache with `ms` left: minutes rounded up while it is warm, an ice cube once it has expired. */
export function cacheStatus(ms) {
	return ms > 0 ? `🔥 ${Math.ceil(ms / 60000)}m` : "🧊";
}

const bound = (target, value) => (typeof value === "function" ? value.bind(target) : value);

function stampedContext(ctx, stamp) {
	let ui;
	return new Proxy(ctx, {
		get(target, key) {
			const value = Reflect.get(target, key);
			if (key !== "ui" || !value || typeof value !== "object") return bound(target, value);
			ui ??= new Proxy(value, {
				get(uiTarget, uiKey) {
					const member = Reflect.get(uiTarget, uiKey);
					if (uiKey === "notify" && typeof member === "function") {
						return (message, ...rest) => member.call(uiTarget, stamp(message, Reflect.get(target, "model")), ...rest);
					}
					return bound(uiTarget, member);
				},
			});
			return ui;
		},
	});
}

export function wrap(pi, upstream) {
	let lastReplyAt = null;
	let cacheUntil = null;
	let statusCtx;
	let timer;
	// Redraws the footer status, then re-arms itself for the moment the minute count drops.
	const showCache = () => {
		clearTimeout(timer);
		const left = cacheUntil === null ? null : cacheUntil - Date.now();
		try {
			if (!statusCtx?.hasUI) return;
			statusCtx.ui.setStatus(STATUS_KEY, left === null ? undefined : cacheStatus(left));
		} catch {
			return; // the context went stale (reload, session switch): its footer is gone
		}
		if (left === null || left <= 0) return;
		timer = setTimeout(showCache, left % 60000 || 60000);
		timer.unref?.();
	};
	const forgetCache = () => {
		cacheUntil = null;
		showCache();
	};
	pi.on("agent_start", () => {
		lastReplyAt = null;
	});
	pi.on("message_start", (event, ctx) => {
		if (event?.message?.role !== "assistant") return;
		lastReplyAt = Date.now();
		const ttl = cacheTtlSeconds(ctx?.model);
		statusCtx = ctx;
		cacheUntil = ttl === undefined ? null : lastReplyAt + ttl * 1000;
		showCache();
	});
	pi.on("model_select", forgetCache);
	pi.on("session_shutdown", forgetCache);
	const stamp = (message, model) => {
		if (typeof message !== "string" || lastReplyAt === null) return message;
		const ttl = cacheTtlSeconds(model);
		const cache = ttl === undefined ? "" : ` (~${clock(lastReplyAt + ttl * 1000).slice(0, 5)})`;
		return `${message.replace(/[.\s]+$/, "")}. ${clock(lastReplyAt)}${cache}`;
	};
	const api = new Proxy(pi, {
		get(target, key) {
			const value = Reflect.get(target, key);
			if (key !== "on" || typeof value !== "function") return bound(target, value);
			return (name, handler, ...rest) =>
				value.call(
					target,
					name,
					name === "agent_end" && typeof handler === "function"
						? (event, ctx, ...more) =>
								handler(event, ctx && typeof ctx === "object" ? stampedContext(ctx, stamp) : ctx, ...more)
						: handler,
					...rest,
				);
		},
	});
	return upstream(api);
}

export default async function tpsPlus(pi) {
	let path;
	try {
		if (typeof senpi.getPackageDir !== "function") throw new Error("senpi has no getPackageDir");
		path = upstreamPath(senpi.getPackageDir());
		const upstream = (await import(pathToFileURL(path).href)).default;
		if (typeof upstream !== "function") throw new Error("no default export");
		await wrap(pi, upstream);
	} catch (error) {
		const reason = error instanceof Error ? error.message : String(error);
		pi.on("session_start", (_event, ctx) => {
			if (ctx?.hasUI) ctx.ui.notify(`tps: senpi tps not loaded (${path ?? "no package dir"}): ${reason}`, "warning");
		});
	}
}
