// omo-tps-plus: runs senpi's own tps extension and adds the time the last reply started to its line.
// Installed as <agentDir>/extensions/tps.js in place of the generated shim. OMO rewrites that file only
// while it starts with its "// Generated by" banner, so this copy survives updates; delete it to get the
// stock shim back on the next start.
import { existsSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import * as senpi from "@code-yeongyu/senpi";

/** Same lookup as senpi's resource-loader uses for the shim it generates. */
export function upstreamPath(packageDir) {
	const flat = join(packageDir, "core", "extensions", "builtin", "tps.js");
	return existsSync(flat) ? flat : join(packageDir, "dist", "core", "extensions", "builtin", "tps.js");
}

export function clock(ms) {
	const date = new Date(ms);
	return [date.getHours(), date.getMinutes(), date.getSeconds()].map((n) => String(n).padStart(2, "0")).join(":");
}

const bound = (target, value) => (typeof value === "function" ? value.bind(target) : value);

function stampedContext(ctx, stamp) {
	let ui;
	return new Proxy(ctx, {
		get(target, key) {
			const value = Reflect.get(target, key);
			if (key !== "ui" || !value || typeof value !== "object") return bound(target, value);
			ui ??= new Proxy(value, {
				get(uiTarget, uiKey) {
					const member = Reflect.get(uiTarget, uiKey);
					if (uiKey === "notify" && typeof member === "function") {
						return (message, ...rest) => member.call(uiTarget, stamp(message), ...rest);
					}
					return bound(uiTarget, member);
				},
			});
			return ui;
		},
	});
}

export function wrap(pi, upstream) {
	let lastReplyAt = null;
	pi.on("agent_start", () => {
		lastReplyAt = null;
	});
	pi.on("message_start", (event) => {
		if (event?.message?.role === "assistant") lastReplyAt = Date.now();
	});
	const stamp = (message) =>
		typeof message === "string" && lastReplyAt !== null
			? `${message.replace(/[.\s]+$/, "")}. Last reply ${clock(lastReplyAt)}`
			: message;
	const api = new Proxy(pi, {
		get(target, key) {
			const value = Reflect.get(target, key);
			if (key !== "on" || typeof value !== "function") return bound(target, value);
			return (name, handler, ...rest) =>
				value.call(
					target,
					name,
					name === "agent_end" && typeof handler === "function"
						? (event, ctx, ...more) =>
								handler(event, ctx && typeof ctx === "object" ? stampedContext(ctx, stamp) : ctx, ...more)
						: handler,
					...rest,
				);
		},
	});
	return upstream(api);
}

export default async function tpsPlus(pi) {
	let path;
	try {
		if (typeof senpi.getPackageDir !== "function") throw new Error("senpi has no getPackageDir");
		path = upstreamPath(senpi.getPackageDir());
		const upstream = (await import(pathToFileURL(path).href)).default;
		if (typeof upstream !== "function") throw new Error("no default export");
		await wrap(pi, upstream);
	} catch (error) {
		const reason = error instanceof Error ? error.message : String(error);
		pi.on("session_start", (_event, ctx) => {
			if (ctx?.hasUI) ctx.ui.notify(`tps: senpi tps not loaded (${path ?? "no package dir"}): ${reason}`, "warning");
		});
	}
}
