# Run from a clone: .\install.ps1  (local copy only, no download)
$ErrorActionPreference = "Stop"
$src = Join-Path $PSScriptRoot "extension\tps.js"
$agent = @($env:OMO_CODING_AGENT_DIR, $env:SENPI_CODING_AGENT_DIR, $env:PI_CODING_AGENT_DIR) | Where-Object { $_ } | Select-Object -First 1
if (-not $agent) { $agent = Join-Path $HOME ".omo\agent" }
if (-not (Test-Path $src)) { throw "missing $src" }
$ext = Join-Path $agent "extensions"
$dst = Join-Path $ext "tps.js"
if (Test-Path $dst) {
	$first = Get-Content $dst -TotalCount 1
	if ($first -notlike "// Generated by *" -and $first -notlike "*omo-tps-plus*") {
		throw "$dst is neither OMO's generated shim nor omo-tps-plus; leaving it alone"
	}
}
$tmp = Join-Path $ext "tps.js.tmp-$PID"
New-Item -ItemType Directory -Force $ext | Out-Null
Copy-Item $src $tmp -Force
Move-Item $tmp $dst -Force
Write-Host "installed -> $dst"
Write-Host "Type /reload in running omo sessions. Delete the file to get the stock tps back."
