#!/usr/bin/env sh
# One-line install, no clone needed:
#   curl -fsSL https://raw.githubusercontent.com/yjacket/omo-tps-plus/master/install.sh | sh
# Run from a clone (sh install.sh) it copies the local file instead.
set -e

url="https://raw.githubusercontent.com/yjacket/omo-tps-plus/master/extension/tps.js"
agent="${OMO_CODING_AGENT_DIR:-${SENPI_CODING_AGENT_DIR:-${PI_CODING_AGENT_DIR:-$HOME/.omo/agent}}}"
ext="$agent/extensions"
dst="$ext/tps.js"
if [ -f "$dst" ]; then
	first="$(head -n 1 "$dst")"
	case "$first" in
		"// Generated by "*|*omo-tps-plus*) ;;
		*) echo "$dst is neither OMO's generated shim nor omo-tps-plus; leaving it alone" >&2; exit 1 ;;
	esac
fi
mkdir -p "$ext"
tmp="$ext/tps.js.tmp-$$"
trap 'rm -f "$tmp"' EXIT
if [ -f "$0" ] && [ -f "$(dirname "$0")/extension/tps.js" ]; then
	cp "$(dirname "$0")/extension/tps.js" "$tmp"
else
	curl -fsSL "$url" -o "$tmp"
fi
mv -f "$tmp" "$dst"
echo "installed -> $dst"
echo "Type /reload in running omo sessions. Delete the file to get the stock tps back."
