#!/usr/bin/env sh
# Run from a clone: sh install.sh  (local copy only, no download)
set -e
src="$(cd "$(dirname "$0")" && pwd)/extension/tps.js"
agent="${OMO_CODING_AGENT_DIR:-${SENPI_CODING_AGENT_DIR:-${PI_CODING_AGENT_DIR:-$HOME/.omo/agent}}}"
[ -f "$src" ] || { echo "missing $src" >&2; exit 1; }
ext="$agent/extensions"
dst="$ext/tps.js"
if [ -f "$dst" ]; then
	first="$(head -n 1 "$dst")"
	case "$first" in
		"// Generated by "*|*omo-tps-plus*) ;;
		*) echo "$dst is neither OMO's generated shim nor omo-tps-plus; leaving it alone" >&2; exit 1 ;;
	esac
fi
tmp="$ext/tps.js.tmp-$$"
mkdir -p "$ext"
cp "$src" "$tmp"
mv -f "$tmp" "$dst"
echo "installed -> $dst"
echo "Type /reload in running omo sessions. Delete the file to get the stock tps back."
