# One-line install, no clone needed:
#   irm https://raw.githubusercontent.com/yjacket/omo-tps-plus/master/install.ps1 | iex
# Run from a clone (.\install.ps1) it copies the local file instead.
& {
	param($root)
	$ErrorActionPreference = "Stop"
	$ProgressPreference = "SilentlyContinue"
	$url = "https://raw.githubusercontent.com/yjacket/omo-tps-plus/master/extension/tps.js"
	$agent = @($env:OMO_CODING_AGENT_DIR, $env:SENPI_CODING_AGENT_DIR, $env:PI_CODING_AGENT_DIR) | Where-Object { $_ } | Select-Object -First 1
	if (-not $agent) { $agent = Join-Path $HOME ".omo\agent" }
	$ext = Join-Path $agent "extensions"
	$dst = Join-Path $ext "tps.js"
	if (Test-Path $dst) {
		$first = Get-Content $dst -TotalCount 1
		if ($first -notlike "// Generated by *" -and $first -notlike "*omo-tps-plus*") {
			throw "$dst is neither OMO's generated shim nor omo-tps-plus; leaving it alone"
		}
	}
	New-Item -ItemType Directory -Force $ext | Out-Null
	$tmp = Join-Path $ext "tps.js.tmp-$PID"
	try {
		$local = if ($root) { Join-Path $root "extension\tps.js" } else { $null }
		if ($local -and (Test-Path $local)) {
			Copy-Item $local $tmp -Force
		} else {
			Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $tmp
		}
		Move-Item $tmp $dst -Force
	} finally {
		Remove-Item $tmp -Force -ErrorAction SilentlyContinue
	}
	Write-Host "installed -> $dst"
	Write-Host "Type /reload in running omo sessions. Delete the file to get the stock tps back."
} $PSScriptRoot
